name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{ https://appliedmmt.com }}
          api-key: ${{ 65431d664a42170f3d5a45a7:cc2ec651a556a2eb67b08bae650df3c6e270ac8028ae7cf4628743a7b6b1cc88 }}
